apiVersion: apps/v1
kind: Deployment
metadata:
  name: credito-app
  namespace: Creditospersonas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credito
  template:
    metadata:
      labels:
        app: credito
    spec:
      containers:
        - name: credito
          image: <DOCKERHUB_USER>/credito-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "<RDS_ENDPOINT>"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "credito_db"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password