apiVersion: apps/v1
kind: Deployment
metadata:
  name: credito-service
  namespace: creditospersonas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credito-service
  template:
    metadata:
      labels:
        app: credito-service
    spec:
      containers:
      - name: credito-service
        image: jenifersanchezops/credito-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-credito.cluster-xxxxxx.us-east-1.rds.amazonaws.com:3306/creditodb
        - name: SPRING_DATASOURCE_USERNAME
          value: admin
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password