apiVersion: v1
kind: Service
metadata:
  name: credito-service
  namespace: creditospersonas
spec:
  selector:
    app: credito-service
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080