apiVersion: v1
kind: Service
metadata:
  name: credito-service
  namespace: Creditospersonas
spec:
  selector:
    app: credito
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer