name: Full Provision and Deploy

on:
  workflow_dispatch:

env:
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_kms_key_alias_base: eks/credito-cluster
  AWS_REGION: us-east-1
  CLUSTER_NAME: credito-cluster
  NAMESPACE: creditospersonas

jobs:
  provision_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Aplicar Terraform
        run: terraform apply -auto-approve

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.0

      - name: Configurar kubectl con EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $(terraform output -raw eks_cluster_name)

      - name: Crear namespace si no existe
        run: |
          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

      - name: Aplicar despliegue de la app
        run: |
          kubectl apply -f ../k8s/deployment.yml -n $NAMESPACE
          kubectl apply -f ../k8s/service.yml -n $NAMESPACE